### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by jamswu** [bigbugcc/OpenWrts#10]
没有支持ipv6版本的固件吗

**Comment by bigbugcc** [comment]
固件默认都开启ipv6的

**Comment by ecrasy** [comment]
需要在config里开启IPv6：Extra packages  --->  ipv6helper

**Comment by jamswu** [comment]
是的，这个好像没开，大神能给开启下ipv6吗 没有ipv6 用着有点不方便

**Comment by ecrasy** [comment]
你可以试试我actions里编译的固件

**Comment by bigbugcc** [comment]
> 是的，这个好像没开，大神能给开启下ipv6吗 没有ipv6 用着有点不方便

用的哪个机型固件

**Comment by jamswu** [comment]
那几个都下载试了 都没有ipv6

**Comment by jamswu** [comment]
x86_64

**Comment by bigbugcc** [comment]
> x86_64

固件里加入了多拨插件，但是之前由于ipv6导致不稳定去除了，现在也不清楚修复没有，下个版本我会跟进一下

**Comment by jamswu** [comment]
感谢大佬
