### ISSUE TITLE
镜像文件类型

### ISSUE THREAD

**Issue by hasayakey** [bigbugcc/OpenWrts#16]
请问x86机器上推荐用什么文件类型的镜像，ext4还是squash啥的

**Comment by bigbugcc** [comment]
x86软路由推荐ext4, 硬路由首选squashfs

**Comment by hasayakey** [comment]
谢谢回复，是openwrt-x86-64-generic-ext4-combined-efi.img还是openwrt-x86-64-generic-ext4-rootfs.img

**Comment by bigbugcc** [comment]
openwrt-x86-64-generic-ext4-combined-efi.img
