### ISSUE TITLE
请问支持VMware吗？

### ISSUE THREAD

**Issue by cheungchingli** [bigbugcc/OpenWrts#18]

**Comment by bigbugcc** [comment]
.vmdk结尾的固件就是

**Comment by cheungchingli** [comment]
好像缺少```.vmx```文件

**Comment by bigbugcc** [comment]
> 
虚拟机你得自己建啊 配置参数(核心，内存....)那些 ，磁盘文件(文件系统)下vmdk

**Comment by cheungchingli** [comment]
我建好了，我的小主机是有双网口的，想装个openwrt做旁路由。我修改了```/etc/config/network```，但是重启后又会还原，不知道什么原因。

**Comment by bigbugcc** [comment]
> 我建好了，我的小主机是有双网口的，想装个openwrt做旁路由。我修改了`/etc/config/network`，但是重启后又会还原，不知道什么原因。

https://bughero.net/archives/openwrt-xu-ni-ji-sheng-ji   只读导致的

**Comment by cheungchingli** [comment]
没有这个分区哦
