### ISSUE TITLE
cpu温度

### ISSUE THREAD

**Issue by xxfire111** [bigbugcc/OpenWrts#21]
大佬求问一下在哪看cpu温度，Raspberry Pi4 最新版固件

**Comment by bigbugcc** [comment]
看这里测试x86正常，验证一下
[https://bughero.net/archives/openwrt_cpu_temp.html](https://bughero.net/archives/openwrt_cpu_temp.html)

**Comment by xxfire111** [comment]
> 看这里测试x86正常，验证一下 https://bughero.net/archives/openwrt_cpu_temp.html
使用第一个命令完美解决，感谢回答
![68{795SLB{F1XAVY75B3X2H](https://user-images.githubusercontent.com/50986622/192444002-8dc4e0ba-1b1a-4a4e-a83c-1c77d695b76e.png)
