### ISSUE TITLE
软件包

### ISSUE THREAD

**Issue by lion6230i** [bigbugcc/OpenWrts#25]
发现软件包里的「已安装软件包」和「可安装软件包」过滤出来是一样的…
硬件是使用R2S，另外语言只有「简中」，能加上「英文」或是「繁中」选项吗？
过滤出来的luci-i18n-也仅有cn可选…

**Comment by bigbugcc** [comment]
固件语言包目前仅添加了简体中文，在下个版本加入，如果可以的话提交PR更好。

**Comment by lion6230i** [comment]
了解，之后若有需求会改用PR。
