### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by mengguyi** [bigbugcc/OpenWrts#28]
我在使用此固件配置 ipv6 时发现没有 DHCPv6 选项

https://github.com/bigbugcc/OpenWrts/assets/73788063/4d207929-cc96-4b19-a98a-5746386dd97f

如视频所示

**Comment by bigbugcc** [comment]
默认创建的WAN是带ipv6的，操作界面没有，可以自行修改接口配置文件实现。

**Comment by mengguyi** [comment]
> 默认创建的WAN是带ipv6的，操作界面没有，可以自行修改接口配置文件实现。

小白不太会改，这个可不可以做到像官方 openwrt 一样在 webui 里改

**Comment by bigbugcc** [comment]
可以，需要自行修改固件配置，已收录下次更新会加入。
