### ISSUE TITLE
考虑添加 Super Lite

### ISSUE THREAD

**Issue by mengguyi** [bigbugcc/OpenWrts#31]
今天编译全失败了，原因是 actions 空间不够了
是否考虑一下删掉部分组件。制造一个超级 Lite 版的
<img width="1280" alt="image" src="https://github.com/bigbugcc/OpenWrts/assets/73788063/ea538f39-e519-4abd-b43f-19395a24f119">

**Comment by bigbugcc** [comment]
感谢你的反馈，确实是因为action空间不足导致的，会通过[其它方法来解决](https://github.com/coolsnowwolf/lede/issues/11480#issuecomment-1694602582)。仓库原本是有Lite版本的想法，但是下载的人很少(我自己算一个😂)，有时间会逐步跟进，也可自行测试后提交PR。

**Comment by mengguyi** [comment]
OK ~
