### ISSUE TITLE
网络唤醒和KMS服务器插件安装代码在哪

### ISSUE THREAD

**Issue by dxs12566** [bigbugcc/OpenWrts#34]
我把 External.config、Rockchip.config、configure.sh、package.sh里按我需要自定义了。该加的加了该删的删了，编译完 网络唤醒 、Turbo ACC 网络加速 和 KMS服务器 还在。实在不知道这仨在哪里删除

**Comment by bigbugcc** [comment]
插件在configs目录中对应机型的配置文件中，以'luci-app'开头

**Comment by dxs12566** [comment]
> 插件在configs目录中对应外围的配置文件中，以'luci-app'开头

这个我知道，我把我不用的luci-app都删掉了，重新加的我需要的luci-app。里面并没有网络唤醒、Turbo ACC网络加速和KMS服务器可是编译出来的依然有
![FireShot Capture 007 - OpenWrts_configs_External config at main · dxs12566_OpenWrts - github com](https://github.com/bigbugcc/OpenWrts/assets/102747655/9793d82c-b7d5-4e66-a82e-3551c9adb845)

**Comment by bigbugcc** [comment]
编译指令中 `deconfig` 会覆盖配置，把那几个选项改为类似 `luci-app-pushbot=m` 就行。

**Comment by dxs12566** [comment]
> `deconfig`会覆盖配置，把那几个选项改为类似

明白了。谢谢提示
