### ISSUE TITLE
怎么编译最基础版本 在docker里面运行 openwrt ?

### ISSUE THREAD

**Issue by gowy222** [bigbugcc/OpenWrts#35]
目前看了很多配置文件，都是openwrt作为docker的host..
而我需要的是反过来,  openwrt作为docker的镜像..
----
怎么编译最基础版本 在docker里面运行 openwrt ?
R5S 宿主机 debian, 已经安装docker跑其他的了，
为了不污染环境，想在docker里面跑openwrt, 【而且不能host网络模式, 毕竟不能影响已有dockers镜像服务】
同时,R5S 是2个lan口，做主路由..怎么构建? 
文档和dockerfile 能不能支援下.

**Comment by bigbugcc** [comment]
可以实现，自行查阅谷歌
