### ISSUE TITLE
无法保存和应用相关配置。

### ISSUE THREAD

**Issue by draftbottle** [bigbugcc/OpenWrts#37]
树莓派4B刷入openwrt，之后更改或者添加配置，无法保存或者应用配置更改。

**Comment by bigbugcc** [comment]
参考[issues/32](https://github.com/bigbugcc/OpenWrts/issues/32#issuecomment-1826739025)

**Comment by draftbottle** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
