### ISSUE TITLE
 一个比赛后的板子，但是我不知道应该刷什么固件

### ISSUE THREAD

**Issue by Miraitowatang** [bigbugcc/OpenWrts#40]
我有一块之前比赛的时候给的板子，内核是ARM Cortex-A7 and RISC-V MCU，它的型号是RV1126，我尝试过刷树莓派4的固件以及X86_64的固件，但是都无法读卡，比赛时使用的与板子通信的方式是通过ADB链接，现在这个板子闲置了我想给它刷成软路由，但是找不到对应刷什么固件，板子长下面这样，配置应该是配置表的第一个EASY EAI NANO 这一款，麻烦帮我看看这个板子应该刷什么固件谢谢
![Image_1701265288816](https://github.com/bigbugcc/OpenWrts/assets/65671239/39ac621f-fcd6-4c72-b3fc-cc8e2cb0ccb2)
![IMG_20240512_223549](https://github.com/bigbugcc/OpenWrts/assets/65671239/7d291cd5-928b-44a9-a683-b42a4894afb9)

**Comment by bigbugcc** [comment]
选固件看处理器型号、架构(Arm)，自行下载LEDE源码编译找一下固件列表有没有这块板子的型号，没有的话得自行找齐板子其它模块的驱动然后自行编译。型号不同，板子的硬件模块都不一样肯定用不了。
