### ISSUE TITLE
树莓派5 ipv6

### ISSUE THREAD

**Issue by xlccccc** [bigbugcc/OpenWrts#45]
我用树莓派5刷入该openwrt固件
光猫为路由模式，ip是 192.168.1.1
openwrt的lan口配置为 ip 192.168.1.10 网关 192.168.1.1，开启DHCP服务器以及DHCPV6（只配置了一个lan口）
手机电脑连接openwrt且将192.168.1.10作为网关可以分配到公网ipv6
但作为openwrt的树莓派无公网ipv6，应该如何配置呢
![image](https://github.com/bigbugcc/OpenWrts/assets/94581757/4957d938-526f-4d93-8c61-6f92a9ff6826)

**Comment by bigbugcc** [comment]
旁路网关获取ipv6你可以试着添加一个新的接口，接口协议改成`DHCPv6客户端`,并划分防火墙为`lan域`。

**Comment by xlccccc** [comment]
树莓派五的固件好像没有`DHCPv6客户端`，是我下的有问题m吗
![image](https://github.com/bigbugcc/OpenWrts/assets/94581757/6ba016e4-9def-4a6b-99a9-a49f69f323c8)
我尝试过lan口改为`192.168.10.1`（其他段），然后设置dhcp服务器，接口用无线网卡
再新建一个wan口作为dhcp客户端，不设置服务器，但是此时自动获取的网关还是光猫的192.168.1.1，将网关换到192.168.10.1是连不上网的，且wan口一直没获取到ip，是什么问题呢
![image](https://github.com/bigbugcc/OpenWrts/assets/94581757/8f74c41b-0b68-4acb-8a0f-7f17b5a15b90)

**Comment by xlccccc** [comment]
我固定ipv6是可以用公网ipv6了，但是还是想不通为什么dhcp获取不到。。

**Comment by bigbugcc** [comment]
> 树莓派五的固件好像没有`DHCPv6客户端`，是我下的有问题m吗 ![image](https://private-user-images.githubusercontent.com/94581757/346316312-6ba016e4-9def-4a6b-99a9-a49f69f323c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNDMxOTUsIm5iZiI6MTcyMDM0Mjg5NSwicGF0aCI6Ii85NDU4MTc1Ny8zNDYzMTYzMTItNmJhMDE2ZTQtOWRlZi00YTZiLTk5YTktYTQ5ZjY5ZjMyM2M4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDA5MDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NjMzOGRmYmEwNjYxYTRhMTE0ZDczNzc3ZjA4YzI0NmZhODc4YTQwYmRkNWI5ZDZmMjZmZDFkZTdkZjNiMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vur9jfSj4SZ30BW5R7s9zF-NwThXhS5rqkjL7nv-NDI) 我尝试过lan口改为`192.168.10.1`（其他段），然后设置dhcp服务器，接口用无线网卡 再新建一个wan口作为dhcp客户端，不设置服务器，但是此时自动获取的网关还是光猫的192.168.1.1，将网关换到192.168.10.1是连不上网的，且wan口一直没获取到ip，是什么问题呢 ![image](https://private-user-images.githubusercontent.com/94581757/346316298-8f74c41b-0b68-4acb-8a0f-7f17b5a15b90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNDMxOTUsIm5iZiI6MTcyMDM0Mjg5NSwicGF0aCI6Ii85NDU4MTc1Ny8zNDYzMTYyOTgtOGY3NGM0MWItMGI2OC00YWNiLThhMGYtN2YxN2I1YTE1YjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDA5MDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMjRkMGZmODlhMDE5ZThhYmU4YmVjMjRkZDBiMjkwNjQ0OGE4ODk2NDg3MzQxODI2Yjk5Y2E1ODQ3Yzc5ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f15_EpuavGXMbxMtQ3-V2zkoBbufceCJvJ0AcXbsbKI)

1. 固件的`DHCPv6`客户端，我会尽快排查解决。
2. 后续问题的描述不太清楚，通常情况下如果你打算创建一个wan口得有对应的物理设备(可以是桥接)，且连接对应的上游网络才行，其次防火墙的域也要注意(没有网络)。DHCP未正常工作设备肯定获取不到ip，按你之前的描述(旁路网关)，你的路由大致应该关闭了DHCP 转由网关接手DHCP了，在接入WAN也就获取不到了，可以多看网上的旁路网关的教程就能搞明白。

**Comment by bigbugcc** [comment]
> 我固定ipv6是可以用公网ipv6了，但是还是想不通为什么dhcp获取不到。。

通常一个设备域不能即做LAN又做WAN，LAN域ipv4的DHCP服务器就是这个道理。

**Comment by xlccccc** [comment]
嗯嗯 麻烦师傅了 还有就是现在固件默认的源有的404了，是不是需要改改
![image](https://github.com/bigbugcc/OpenWrts/assets/94581757/764ca0f0-40aa-4733-9b54-025fc8d8f747)

**Comment by xlccccc** [comment]
![image](https://github.com/bigbugcc/OpenWrts/assets/94581757/fad4f57f-f7e3-4d6b-a52d-523940a45f96)
然后装的python3是会报错的

**Comment by bigbugcc** [comment]
> 嗯嗯 麻烦师傅了 还有就是现在固件默认的源有的404了，是不是需要改改 ![image](https://private-user-images.githubusercontent.com/94581757/346326193-764ca0f0-40aa-4733-9b54-025fc8d8f747.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNDg5NzUsIm5iZiI6MTcyMDM0ODY3NSwicGF0aCI6Ii85NDU4MTc1Ny8zNDYzMjYxOTMtNzY0Y2EwZjAtNDBhYS00NzMzLTliNTQtMDI1ZmM4ZDhmNzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDEwMzc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYWQxNzhhMDIzODU2MmUzOWRiMWE1MjE2NmJjYTM4NmZkYzI3OTBmMzMyNDVmMDE2YzExYTg1OWQzM2M3NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J4xSroCg9RvreGF4r4JX51NY5z6d79A4cXAs6uXyvj8)

固件自带的软件源，可自行替换阿里、腾讯、中科大。
