### ISSUE TITLE
如果不需要docker和istore应该怎么配置？ What if you don't need  docker and the istore?

### ISSUE THREAD

**Issue by theo-yz** [bigbugcc/OpenWrts#46]
因功能太多，导致R68s无法稳定运行，希望去除docker和istore，应该怎么配置？ 非常感谢

R68s cannot run stably due to too many functions. I want to remove docker and istore. How should I configure it? Thank you very much

Sat Jul 27 13:50:54 2024 daemon.notice procd: /etc/rc.d/S45nfs: exportfs: could not open /var/lib/nfs/.etab.lock for locking: errno 2 (No such file or directory)
Sat Jul 27 13:50:54 2024 daemon.notice procd: /etc/rc.d/S45nfs: exportfs: could not open /var/lib/nfs/.etab.lock for locking: errno 2 (No such file or directory)
Sat Jul 27 13:50:54 2024 daemon.notice procd: /etc/rc.d/S45nfs: exportfs: can't lock /var/lib/nfs/etab for writing
Sat Jul 27 13:50:54 2024 daemon.notice procd: /etc/rc.d/S50autoreboot: Command failed: ubus call service delete { "name": "cron" } (Not found)
Sat Jul 27 13:50:54 2024 daemon.notice procd: /etc/rc.d/S50autoreboot: Auto REBOOT has started.

**Comment by bigbugcc** [comment]
在编译的配置文件中注释或删除不需要的`luci_app`重新编译就行。
