### ISSUE TITLE
所以之前的版本有没有留档，新的JS的luci太难用了，而且很多插件都不支持了

### ISSUE THREAD

**Issue by adfnkjasd** [bigbugcc/OpenWrts#52]
### 详细叙述

lede更了新的luci，很多之前的插件都用不了了，docker更是直接瘫痪
补充：因为更新了新的luci，新版本的主题argon不支持老的18.0.6的luci了，会导致进入后台时显示错误信息，下次更新的时候换一下源吧，master分支23的才是最新的，现在应该获取的还是18.0.6的

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

openwrt

### 详细日志

10月8日之前的

**Comment by bigbugcc** [comment]
确实如此，luci拉取的还是[18.版本](https://github.com/bigbugcc/OpenWrts/blob/399a4907203c2861ed3a3c649bec2789d75cc35e/configure.sh#L22)，我目前使用的还是两个月前编译的固件😅。大致看了下仓库 大雕在17号修改了源，这个更新挺大的，我暂时修改源至老版本等待其它插件更新同步。

**Comment by adfnkjasd** [comment]
> 确实如此，luci拉取的还是[18.版本](https://github.com/bigbugcc/OpenWrts/blob/399a4907203c2861ed3a3c649bec2789d75cc35e/configure.sh#L22)，我目前使用的还是两个月前编译的固件😅。大致看了下仓库 大雕在17号修改了源，这个更新挺大的，我暂时修改源至老版本等待其它插件更新同步。

请问还有老版本的固件吗，如果有的话老版本固件放一下Releases吧，现在这个怎么用怎么难受😅，感谢

**Comment by bigbugcc** [comment]
老版本的固件没有留存😂，Action正在重新编译了，大概2-3个小时，稍等下。

**Comment by adfnkjasd** [comment]
> 老版本的固件没有留存😂，Action正在重新编译了，大概2-3个小时，稍等下。

ok，那我这里就close了
