### ISSUE TITLE
能否把zerotier增加为常用插件

### ISSUE THREAD

**Issue by wj55** [bigbugcc/OpenWrts#9]
大佬，你好：
我最近用树莓派4B做软路由，发现该固件很好用，就是缺一个zerotier。自己在“软件包”内安装了zerotier，但刷新了界面或重启了设备，还是没有相关的配置栏显示。希望大佬能把zerotier添加为常用固件，内网穿透很好用。望大佬抽点小空，修改一下。谢谢

**Comment by bigbugcc** [comment]
后续会考虑加入
